console.log(null == undefined); // true
console.log(null === undefined); // false
console.log(null == 0); // false
//console.log( >= 0); // true
//console.log( <= 0); // true
//console.log( > 0); // false
console.log(undefined == 0); // false
console.log(undefined >= 0); // false
console.log(undefined <= 0); // false